-- Sakai Video Training Module Schema (MySQL)

CREATE TABLE IF NOT EXISTS VTM_VIDEO (
  VIDEO_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR(99) NOT NULL,
  OWNER_ID VARCHAR(99) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  DESCRIPTION LONGTEXT,
  PROVIDER_TYPE VARCHAR(16) NOT NULL DEFAULT 'NATIVE',
  SOURCE_ID VARCHAR(1024) NOT NULL,
  FILE_SIZE_BYTES BIGINT,
  VISIBILITY_SCOPE VARCHAR(16) NOT NULL DEFAULT 'COURSE',
  PUBLICATION_STATUS VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
  LESSON_ORIGIN_RESTRICTED BOOLEAN NOT NULL DEFAULT FALSE,
  RELEASE_DATE BIGINT,
  RETRACT_DATE BIGINT,
  REQUIRED_VIEW_PERMISSION VARCHAR(99) NOT NULL DEFAULT 'video.training.view',
  CREATED_ON BIGINT NOT NULL,
  MODIFIED_ON BIGINT NOT NULL,
  INDEX IDX_VTM_VIDEO_SITE_ID (SITE_ID),
  INDEX IDX_VTM_VIDEO_SITE_MODIFIED_ID (SITE_ID, MODIFIED_ON DESC, VIDEO_ID),
  INDEX IDX_VTM_VIDEO_RELEASE_RETRACT (SITE_ID, RELEASE_DATE, RETRACT_DATE),
  INDEX IDX_VTM_VIDEO_SITE_TITLE_MODIFIED (SITE_ID, TITLE, MODIFIED_ON DESC),
  FULLTEXT INDEX IDX_VTM_VIDEO_FT_TITLE_DESC (TITLE, DESCRIPTION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VTM_CATEGORY (
  CATEGORY_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR(99) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  PARENT_CATEGORY_ID VARCHAR(36),
  SORT_ORDER INT NOT NULL DEFAULT 0,
  CREATED_ON BIGINT NOT NULL,
  MODIFIED_ON BIGINT NOT NULL,
  INDEX IDX_VTM_CATEGORY_SITE (SITE_ID),
  INDEX IDX_VTM_CATEGORY_PARENT (PARENT_CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VTM_VIDEO_CATEGORY (
  VIDEO_CATEGORY_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  VIDEO_ID VARCHAR(36) NOT NULL,
  CATEGORY_ID VARCHAR(36) NOT NULL,
  CREATED_ON BIGINT NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES VTM_VIDEO(VIDEO_ID) ON DELETE CASCADE,
  FOREIGN KEY (CATEGORY_ID) REFERENCES VTM_CATEGORY(CATEGORY_ID) ON DELETE CASCADE,
  UNIQUE KEY UQ_VTM_VIDEO_CATEGORY (VIDEO_ID, CATEGORY_ID),
  INDEX IDX_VTM_VIDEO_CATEGORY_VIDEO (VIDEO_ID),
  INDEX IDX_VTM_VIDEO_CATEGORY_CATEGORY (CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VTM_LESSON_LINK (
  LESSON_LINK_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR(99) NOT NULL,
  VIDEO_ID VARCHAR(36) NOT NULL,
  LESSON_PAGE_ID VARCHAR(99) NOT NULL,
  LESSON_ITEM_ID VARCHAR(99),
  CREATED_ON BIGINT NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES VTM_VIDEO(VIDEO_ID) ON DELETE CASCADE,
  INDEX IDX_VTM_LESSON_LINK_VIDEO (VIDEO_ID),
  INDEX IDX_VTM_LESSON_LINK_SITE_PAGE (SITE_ID, LESSON_PAGE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VTM_CAPTION (
  CAPTION_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  VIDEO_ID VARCHAR(36) NOT NULL,
  LANGUAGE_TAG VARCHAR(35) NOT NULL,
  CONTENT_REFERENCE VARCHAR(1024),
  TRANSCRIPT_TEXT VARCHAR(12000),
  CREATED_ON BIGINT NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES VTM_VIDEO(VIDEO_ID) ON DELETE CASCADE,
  UNIQUE KEY UQ_VTM_CAPTION_VIDEO_LANG (VIDEO_ID, LANGUAGE_TAG),
  INDEX IDX_VTM_CAPTION_VIDEO_LANG (VIDEO_ID, LANGUAGE_TAG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS VTM_ANALYTICS_EVENT (
  EVENT_ID VARCHAR(36) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR(99) NOT NULL,
  VIDEO_ID VARCHAR(36) NOT NULL,
  USER_ID VARCHAR(99) NOT NULL,
  EVENT_TYPE VARCHAR(32) NOT NULL,
  EVENT_TIME BIGINT NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES VTM_VIDEO(VIDEO_ID) ON DELETE CASCADE,
  INDEX IDX_VTM_ANALYTICS_SITE_ID (SITE_ID),
  INDEX IDX_VTM_ANALYTICS_VIDEO_ID (VIDEO_ID),
  INDEX IDX_VTM_ANALYTICS_SITE_EVENTTYPE (SITE_ID, EVENT_TYPE),
  INDEX IDX_VTM_ANALYTICS_VIDEO_EVENTTIME (VIDEO_ID, EVENT_TIME DESC),
  INDEX IDX_VTM_ANALYTICS_EVENTTIME (EVENT_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
