-- Sakai Video Training Module Schema (Oracle)

CREATE TABLE VTM_VIDEO (
  VIDEO_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR2(99) NOT NULL,
  OWNER_ID VARCHAR2(99) NOT NULL,
  TITLE VARCHAR2(255) NOT NULL,
  DESCRIPTION CLOB,
  PROVIDER_TYPE VARCHAR2(16) NOT NULL DEFAULT 'NATIVE',
  SOURCE_ID VARCHAR2(1024) NOT NULL,
  FILE_SIZE_BYTES NUMBER,
  VISIBILITY_SCOPE VARCHAR2(16) NOT NULL DEFAULT 'COURSE',
  PUBLICATION_STATUS VARCHAR2(16) NOT NULL DEFAULT 'PUBLISHED',
  LESSON_ORIGIN_RESTRICTED NUMBER(1) DEFAULT 0 NOT NULL,
  RELEASE_DATE NUMBER,
  RETRACT_DATE NUMBER,
  REQUIRED_VIEW_PERMISSION VARCHAR2(99) NOT NULL DEFAULT 'video.training.view',
  CREATED_ON NUMBER NOT NULL,
  MODIFIED_ON NUMBER NOT NULL
);

CREATE INDEX IDX_VTM_VIDEO_SITE_ID ON VTM_VIDEO(SITE_ID);
CREATE INDEX IDX_VTM_VIDEO_SITE_MODIFIED_ID ON VTM_VIDEO(SITE_ID, MODIFIED_ON DESC, VIDEO_ID);
CREATE INDEX IDX_VTM_VIDEO_RELEASE_RETRACT ON VTM_VIDEO(SITE_ID, RELEASE_DATE, RETRACT_DATE);
CREATE INDEX IDX_VTM_VIDEO_SITE_TITLE_MODIFIED ON VTM_VIDEO(SITE_ID, TITLE, MODIFIED_ON DESC);

CREATE TABLE VTM_CATEGORY (
  CATEGORY_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR2(99) NOT NULL,
  NAME VARCHAR2(255) NOT NULL,
  PARENT_CATEGORY_ID VARCHAR2(36),
  SORT_ORDER NUMBER DEFAULT 0 NOT NULL,
  CREATED_ON NUMBER NOT NULL,
  MODIFIED_ON NUMBER NOT NULL
);

CREATE INDEX IDX_VTM_CATEGORY_SITE ON VTM_CATEGORY(SITE_ID);
CREATE INDEX IDX_VTM_CATEGORY_PARENT ON VTM_CATEGORY(PARENT_CATEGORY_ID);

CREATE TABLE VTM_VIDEO_CATEGORY (
  VIDEO_CATEGORY_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  VIDEO_ID VARCHAR2(36) NOT NULL,
  CATEGORY_ID VARCHAR2(36) NOT NULL,
  CREATED_ON NUMBER NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES VTM_VIDEO(VIDEO_ID) ON DELETE CASCADE,
  FOREIGN KEY (CATEGORY_ID) REFERENCES VTM_CATEGORY(CATEGORY_ID) ON DELETE CASCADE,
  UNIQUE (VIDEO_ID, CATEGORY_ID)
);

CREATE INDEX IDX_VTM_VIDEO_CATEGORY_VIDEO ON VTM_VIDEO_CATEGORY(VIDEO_ID);
CREATE INDEX IDX_VTM_VIDEO_CATEGORY_CATEGORY ON VTM_VIDEO_CATEGORY(CATEGORY_ID);

CREATE TABLE VTM_LESSON_LINK (
  LESSON_LINK_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR2(99) NOT NULL,
  VIDEO_ID VARCHAR2(36) NOT NULL,
  LESSON_PAGE_ID VARCHAR2(99) NOT NULL,
  LESSON_ITEM_ID VARCHAR2(99),
  CREATED_ON NUMBER NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES VTM_VIDEO(VIDEO_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_VTM_LESSON_LINK_VIDEO ON VTM_LESSON_LINK(VIDEO_ID);
CREATE INDEX IDX_VTM_LESSON_LINK_SITE_PAGE ON VTM_LESSON_LINK(SITE_ID, LESSON_PAGE_ID);

CREATE TABLE VTM_CAPTION (
  CAPTION_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  VIDEO_ID VARCHAR2(36) NOT NULL,
  LANGUAGE_TAG VARCHAR2(35) NOT NULL,
  CONTENT_REFERENCE VARCHAR2(1024),
  TRANSCRIPT_TEXT VARCHAR2(4000),
  CREATED_ON NUMBER NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES VTM_VIDEO(VIDEO_ID) ON DELETE CASCADE,
  UNIQUE (VIDEO_ID, LANGUAGE_TAG)
);

CREATE INDEX IDX_VTM_CAPTION_VIDEO_LANG ON VTM_CAPTION(VIDEO_ID, LANGUAGE_TAG);

CREATE TABLE VTM_ANALYTICS_EVENT (
  EVENT_ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  SITE_ID VARCHAR2(99) NOT NULL,
  VIDEO_ID VARCHAR2(36) NOT NULL,
  USER_ID VARCHAR2(99) NOT NULL,
  EVENT_TYPE VARCHAR2(32) NOT NULL,
  EVENT_TIME NUMBER NOT NULL,
  FOREIGN KEY (VIDEO_ID) REFERENCES VTM_VIDEO(VIDEO_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_VTM_ANALYTICS_SITE_ID ON VTM_ANALYTICS_EVENT(SITE_ID);
CREATE INDEX IDX_VTM_ANALYTICS_VIDEO_ID ON VTM_ANALYTICS_EVENT(VIDEO_ID);
CREATE INDEX IDX_VTM_ANALYTICS_SITE_EVENTTYPE ON VTM_ANALYTICS_EVENT(SITE_ID, EVENT_TYPE);
CREATE INDEX IDX_VTM_ANALYTICS_VIDEO_EVENTTIME ON VTM_ANALYTICS_EVENT(VIDEO_ID, EVENT_TIME DESC);
CREATE INDEX IDX_VTM_ANALYTICS_EVENTTIME ON VTM_ANALYTICS_EVENT(EVENT_TIME);
